- id: doi:https://doi.org/10.31234/osf.io/8mxy3_v1
  date: '2025-04-18'
  type: paper
  description: In a novel task combining multiple-object tracking with whole-report, Piotr and William examine how the contralateral delay activity (an event-related potential shown tracking load and working memory load in separate tasks) reacts in the combined task.
  image: /images/projects/boston_dynamics.gif
  buttons:
    - type: preprint
      text: Preprint
      link: https://osf.io/preprints/psyarxiv/8mxy3_v1
  tags:
    - contralateral delay activity
    - multiple-object tracking
    - pointers

- id: doi:10.1177/09567976241263002
  date: '2024-08-19'
  type: paper
  description: Using multivariate decoding, Henry Jones shows that neural signals for the number of items stored in working memory are insensitive to breadth and position of spatial attention. This suggests that while related, spatial attention is functionally dissociable from the selection and maintenace of information in mind.
  image: /images/jones_psychsci.png
  buttons:
    - type: website
      text: Journal Page
      link: https://journals.sagepub.com/doi/abs/10.1177/09567976241263002
    - type: data
      text: Data and Code
      link: https://osf.io/8vur2/
  tags:
    - multivariate decoding
    - spatial attention
    - representations
    - pointers

- id: doi:10.1037/xge0001479
  date: '2023-09-11'
  type: paper
  description: Using a new 'conjunction whole-report' paradigm, we find that visual working memory is limited by object-based encoding, but that features can also be independently lost from the memory for an item. We developed a computational model that captures both feature-based and object-based effects.
  image: /images/conjunction_whole-report.png
  buttons:
    - type: preprint
      text: Preprint
      link: https://osf.io/preprints/psyarxiv/mc5p9
    - type: website
      text: Journal Page
      link: https://doi.org/10.1037/xge0001479
    - type: data
      text: Data and Code
      link: https://osf.io/wjr7u/
  tags:
    - whole-report
    - computational modeling
    - capacity limits
    - representations

- id: doi:10.3758/s13423-023-02356-5
  authors:
    - William X. Q. Ngiam
  date: '2023-08-28'
  type: paper
  description: A review comparing and contrasting current theories and models of visual working memory, leading to a 'theory map'. The hope is that the theory map provides a common space to better discuss various empirical phenomena and move towards a model-based approach to research visual working memory.
  image: /images/theory_map.png
  buttons:
    - type: preprint
      text: Preprint
      link: https://psyarxiv.com/g8erx
    - type: website
      text: Journal Page
      link: https://link.springer.com/article/10.3758/s13423-023-02356-5
  tags:
    - theory map
    - pointers
    - representations

- id: doi:10.3758/s13414-022-02631-y
  date: '2022-12-20'
  type: paper
  description: We developed a paradigm that leads to distinct patterns of responses produced by imprecise memories, and produced by guesses. We find clear evidence for guessing, in line with the notion of an item limit in visual working memory, but also suggest a resource-based model that can explain the observed results.
  image: /images/guess_bands.png
  buttons:
    - type: preprint
      text: Preprint
      link: https://psyarxiv.com/bkdya
    - type: website
      text: Journal Page
      link: https://doi.org/10.3758/s13414-022-02631-y
    - type: data
      text: Data and Code
      link: https://osf.io/64rdq/
  tags:
    - guesses
    - whole-report
    - capacity limits

- id: doi:10.1111/psyp.13791
  date: '2021-02-10'
  type: paper
  description: A downsampling analysis of two large datasets measuring the contralateral delay activity (CDA), estimating the statistical power for detecting the presence of the CDA and its set-size effects. We provide an app that can estimate the statistical power for a given number of trials and subjects.
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/8084110/bin/nihms-1691056-f0006.jpg
  buttons:
    - type: preprint
      text: Preprint
      link: https://psyarxiv.com/nbvkc
    - type: website
      text: Journal Page
      link: https://onlinelibrary.wiley.com/doi/10.1111/psyp.13791
    - type: app
      text: Online App
      link: https://williamngiam.shinyapps.io/CDAPower/
  tags:
    - contralateral delay activity
    - statistical power
  
- id: doi:10.1037/xge0000649
  date: '2019-08-01'
  type: paper
  description: When to-be-remembered displays contain statistical regularities, we can recall more items overall. However, this is contingent on subjects having explicit awareness of the regularities, supporting a long-term memory 'chunking' account.
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7375746/bin/nihms-1605259-f0006.jpg
  buttons:
    - type: preprint
      link: https://awhvogellab.files.wordpress.com/2019/06/ngiam-brissenden-and-awh-2019-preprint.pdf
    - type: website
      text: Journal Page
      link: https://psycnet.apa.org/record/2019-42672-001
    - type: data
      text: Data and Code
      link: https://osf.io/9c4rj/
  tags:
    - chunking
    - long-term memory
    - associative learning
  
- id: doi:10.1037/XLM0000682
  date: '2019-10-01'
  type: paper
  description: Visual working memory is better for familiar letters compared to unfamiliar characters, including artifical characters matched in stimulus complexity. This suggests learned experience can benefit the encoding of visual information.
  image: /images/familiar_letters.png
  buttons: 
    - type: preprint
      link: https://psyarxiv.com/cxkw5
    - type: website
      text: Journal Page
      link: https://psycnet.apa.org/record/2018-64925-001
    - type: data
      text: Data and Code
      link: https://osf.io/4by2f/
  tags:
    - familiarity
    - long-term memory
 